### PR TITLE
Added a \lesssim and \gtrsim to symbol and fixed quote handling in prettifyer

### PR DESCRIPTION
**Pull request by guraltsev**
Sorry I put the two issues together (I am rather new to this)

# Adding new symbols
I added \lesssim and \gtrsim symbols to the list in ml/symbols with corresponding Unicode glyphs.

# Handling quotes in prettyfier

When prettifying the quote character gets considered as a punctuation
mark. This allows prettyfying expressions like $\phi'$. Fixes issue #10.
However, I am not very familiar with the code so I added the single quote `'` as a punctuation symbol via `with-syntax-table` inside `magic-latex-enable-pretty-symbols` in `ml/jit-prettifier`.  Maybe one could just put it into `ml/syntax-table`?

### CODE REVIEW

**Comment by zk-phi** [comment]
> Maybe one could just put it into `ml/syntax-table` ?

I think it's okay to set `'` as a punctuation, since I don't so much feel the advantage of setting it as a word constructor. How do you think ?

**Comment by guraltsev** [comment]
I think that could be a good idea. Maybe we should include a comment in the definition of `ml/syntax-table` so that we know where to look for in case of problems. Do I understand correctly that `ml/syntax-table` gets used only when running commands from `magic-latex-buffer` but it doesn't influence other modes that may be enabled on the buffer?

**Comment by guraltsev** [comment]
I changed my pull request according to what you suggested.

**Comment by zk-phi** [comment]
Merged. Thanks for your contribution!

**Pull request merged**
